name: scheduled execution
on: 
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         │ │ │ │ │
    #         * * * * *
    - cron: '41 * * * *'
jobs: # tarefas que serão executadas
    e2e_tests: # nome da task
        runs-on: ubuntu-latest # imagem que será utilizada
        steps: # passos que serão executadas na task
            - name: checkout project
              uses: actions/checkout@v4

            - name: install nodejs
              uses: actions/setup-node@v4
              with: 
                node-version: 24.x

            - name: install yarn
              run: npm install -g yarn

            - name: installing dependencies
              run: yarn

            - name: installing playwright browsers
              run: yarn playwright install

            - name: runing e2e tests
              run: yarn run e2e
            
             